import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import OverlayProvider from "@/context/overlay/OverlayProvider";

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <OverlayProvider>
      <html
        lang="en"
        className={`${poppins.variable} h-full antialiased`}
      >

        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </OverlayProvider>
  );
}


export default RootLayout;